FROM registry.access.redhat.com/ubi7/ubi:latest

ARG GO_PACKAGE_PATH=github.com/redhat-developer/helm

ENV GIT_COMMITTER_NAME      devtools
ENV GIT_COMMITTER_EMAIL     devtools@redhat.com

ENV LANG                    en_US.utf8

ENV GOPATH                  /go
ENV GOROOT                  /opt/go
ENV GOCACHE                 /tmp/.gocache

ENV PATH                    $GOPATH/bin:$GOROOT/bin:$PATH

RUN yum install -y --quiet --setopt=skip_missing_names_on_install=False \
    git \
    make \
    gcc \
    rh-python36-python-virtualenv \
    && yum clean all

WORKDIR /tmp

RUN mkdir -p $GOPATH/bin
RUN mkdir -p $GOROOT
RUN mkdir -p $GOCACHE

RUN curl -Lo go.tar.gz https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz && tar -xf go.tar.gz -C / && rm -vf go.tar.gz

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl $GOPATH/bin/

RUN mkdir -p ${GOPATH}/src/${GO_PACKAGE_PATH}/

WORKDIR ${GOPATH}/src/${GO_PACKAGE_PATH}

COPY . .

RUN chmod -R go+wr $GOPATH $GOROOT $GOCACHE

ENTRYPOINT [ "/bin/bash" ]