name: build-test
on:
  push:
    branches:
      - "main"
      - "dev-v3"
      - "release-**"
  pull_request:
    branches:
      - "main"
      - "dev-v3"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/go-toolset:1.26
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
      - name: Mark workspace as safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test source headers are present
        run: make test-source-headers
      - name: Check if go modules need to be tidied
        run: go mod tidy -diff
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build
