name: golangci-lint

on:
  push:
  pull_request:

permissions:  
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/go-toolset:1.26
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - name: Mark workspace as safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Add variables to environment file
        run: cat ".github/env" >> "$GITHUB_ENV"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a #pin@9.3.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
